name: Release to Google Play

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      track:
        description: 'Release track'
        required: true
        default: 'internal'
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      VERSION_NAME: ${{ github.ref_name }}
      VERSION_CODE: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode release keystore
        run: |
          echo -n "${{ secrets.KEYSTORE_BASE64 }}" | tr -d '\r\n' | base64 -d > keystore.jks

      - name: Create Play Store credentials
        run: |
          echo '${{ secrets.PLAY_STORE_CREDENTIALS }}' > play-store-credentials.json

      - name: Generate release notes
        run: ./gradlew generateReleaseNotes

      - name: Build release AAB
        run: ./gradlew bundleRelease
        env:
          KEYSTORE_PATH: ../keystore.jks

      - name: Build release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: ../keystore.jks

      - name: Upload to Play Store
        run: ./gradlew publishBundle
        env:
          PLAY_TRACK: ${{ github.event.inputs.track || 'internal' }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ env.VERSION_NAME }}
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab-${{ env.VERSION_NAME }}
          path: app/build/outputs/bundle/release/*.aab

      - name: Upload mapping files
        uses: actions/upload-artifact@v4
        with:
          name: mapping-files-${{ env.VERSION_NAME }}
          path: app/build/outputs/mapping/release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
          body_path: fastlane/metadata/android/en-US/changelogs/${{ github.run_number }}.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
